# Generated by Django 5.2.1 on 2025-06-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_user_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
    ]
